/* (Beta) Export of data model TechnicalCabinetDevice of the subject dataModel.Energy for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE TechnicalCabinetDevice_doorType_type AS ENUM ('mixed', 'other', 'solid', 'transparent');
CREATE TYPE TechnicalCabinetDevice_installationMode_type AS ENUM ('aerial', 'ground', 'other', 'pole', 'roofing', 'underground', 'wall');
CREATE TYPE TechnicalCabinetDevice_possibilityOfUse_type AS ENUM ('mixed', 'mobile', 'other', 'stationary');
CREATE TYPE TechnicalCabinetDevice_type AS ENUM ('TechnicalCabinetDevice');
CREATE TYPE TechnicalCabinetDevice_typeOfUse_type AS ENUM ('indoor', 'mixed', 'outdoor', 'other');
CREATE TABLE TechnicalCabinetDevice (
  "address" JSON,
  "alternateName" TEXT,
  "application" JSON,
  "areaServed" TEXT,
  "brandName" TEXT,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateLastReported" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "description" TEXT,
  "designMaterials" JSON,
  "dimension" JSON,
  "documentation" TEXT,
  "doorClosingMode" JSON,
  "doorCount" NUMERIC,
  "doorOpeningAngle" NUMERIC,
  "doorType" TechnicalCabinetDevice_doorType_type,
  "exteriorCoating" JSON,
  "exteriorFinish" JSON,
  "id" TEXT PRIMARY KEY,
  "installationCondition" JSON,
  "installationMode" TechnicalCabinetDevice_installationMode_type,
  "interiorCoating" JSON,
  "internalDimension" JSON,
  "location" JSON,
  "manufacturerName" TEXT,
  "maximumSystemVoltage" NUMERIC,
  "modelName" TEXT,
  "name" TEXT,
  "operatingTemperature" JSON,
  "owner" JSON,
  "possibilityOfUse" TechnicalCabinetDevice_possibilityOfUse_type,
  "protectionIK" NUMERIC,
  "protectionIP" TEXT,
  "protectionOthers" JSON,
  "refDevice" JSON,
  "refDeviceList" JSON,
  "refPointOfInterest" JSON,
  "seeAlso" JSON,
  "serialNumber" TEXT,
  "source" TEXT,
  "type" TechnicalCabinetDevice_type,
  "typeOfUse" TechnicalCabinetDevice_typeOfUse_type,
  "ventilationMode" JSON,
  "weight" NUMERIC
);